name: mobilicis_assignment
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  # fast_cached_network_image: ^1.2.0
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_multi_select_items: ^0.4.2
  flutter_svg: ^2.0.7
  get: ^4.6.5
  http: ^1.1.0
  intl: ^0.18.1
  multi_select_flutter: ^4.1.3
  path_provider: ^2.0.15
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
